Fix no such file errors for r11_etc/ files
Fixes the following error when running make.sh:

        cp: cannot stat 'etc/FONT00.FNT': No such file or directory
        ../../py-src/extract_font.py
        Extracting FONT00.FNT to PNGs
        Traceback (most recent call last):
          File "/home/mark/Desktop/R11-psp-english/text/font/../../py-src/extrac
          File "/home/mark/Desktop/R11-psp-english/text/font/../../py-src/extrac
t_font.py", line 360, in <module>
            main();
          File "/home/mark/Desktop/R11-psp-english/text/font/../../py-src/extract_font.py", line 322, in main
            font = unpackFont(srcpath);
          File "/home/mark/Desktop/R11-psp-english/text/font/../../py-src/extract_font.py", line 41, in unpackFont
            f=open(path, "rb")
        FileNotFoundError: [Errno 2] No such file or directory: 'FONT00.FNT'

unpack_afs.sh was writing files to the directory "r11_etc". However, the
error trace indicates that the rest of the patching process tries to
look for those files under a directory named "etc".

This commit modifies unpack_afs.sh so that at the end of the script,
the "r11_etc" directory is renamed to "etc".